# Generated by Django 4.0.6 on 2022-07-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cena')),
                ('time_to_prepare', models.IntegerField(blank=True, null=True, verbose_name='Czas przygotowania ( w min.)')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('last_modified_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Data aktualizacji')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='Czy wegańskie?')),
                ('photo', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('last_modified_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Data aktualizacji')),
                ('dishes', models.ManyToManyField(to='menu_app.dish', verbose_name='Dania')),
            ],
        ),
    ]
