# Generated by Django 4.0.6 on 2022-07-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
